name: CI deployment
on: push
jobs:
  fetch-code:
    runs-on: ubuntu-latest
    steps:
      - name: get the code from repo
        uses: actions/checkout@v5
      - name: list the files    
        run: |
          ls -l
          pwd
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code
        uses: actions/checkout@v5
      - name: check java and maven version
        run: |
          java -version
          mvn --version  
      - name: build the code
        run:  mvn clean package  
      - name: list files
        run: |
          ls -l  
